### ISSUE TITLE
Romper todo

### ISSUE THREAD

**Issue by enolgargon** [Arquisoft/dechat_es2b#45]
Siento decilo así, pero lo que tamos faciendo no está valiendo de nada. Os lo podría decir en persona, por whatsapp o de muchas formas, pero prefiero que quede aquí escrito.
Como veis en las clases de teoría estamos convirtiendo la aplicación en un antipatrón, antes de que crezca y nos encontremos con algo que no podemos manejar propongo buscar otra forma de plantearlo todo bien.
Os dejo un esquema de como pienso que debe ser:
[Esquema](https://drive.google.com/open?id=1pH5g1y0l7USV9Q_U7DeyuniXEL8NnPTn)
Con este esquema

- Tenemos el modelo en el centro
- Angular no aparece para nada, podría ser reemplazable, ya que solo está presente en la parte de vista
- Tenemos una estructura escalonada en la que cada capa se comunica con la siguiente
- Podemos sustituir el pod por un mock cambiando solo una clase

Mi idea es crear una nueva rama: developAlt e intentar seguir esta linea por ahí sin dejar tirada la develop que tenemos ahora. Si vemos que con developAlt conseguimos algo mejor que sustituya al develop anterior.
¿Qué os parece @acg96 @TomasArguelles?

**Comment by TomasArguelles** [comment]
Me parece buena idea

**Comment by acg96** [comment]
La idea me parece bien, lo que tenemos que concretar es si empezamos ya de ya con esa nueva versión o no. Recalcar que en el esquema hay un fallo en la parte del modelo, se llama mensaje a lo que deberia ser contacto y viceversa, pero por el resto lo veo bien. 

Ahora como un apunte:
Quizás otro enfoque que se podría dar (sería ir un paso más allá) es realizarlo mediante tres módulos distribuidos que se comuniquen por http. Es decir, que el modelo y la capa de negocio esté en un módulo, en otro módulo a parte la gestión a base de datos y en otro la vista. De esa forma si se quieren cambiar los POD por otra bbdd tan solo sería hacer esa parte (modulo) y no habría que compilarlo todo porque el modelo y la capa de negocio ya estarían funcionando como un servicio a parte. Lo mismo con la vista, que enviaría peticiones y recibiría respuestas del modulo de negocio y modelo. Por dentro la estrucutura de cada módulo podría ser la misma que se indicaba en el esquema. La ventaja de esto es que no habría dependencias del lenguaje entre las partes, es decir, si los POD se gestionan mejor con typescript o javascript se podría hacer esa parte en ese lenguaje y ya para el resto pues el lenguaje más acorde. Los test de igual manera podrían ser otro modulo e incluso se podrían testear los modulos individualmente.
