### ISSUE TITLE
Inbox para notificación de mensajes en conversaciones individuales

### ISSUE THREAD

**Issue by acg96** [Arquisoft/dechat_es2b#76]
Utilizar inbox para notificar de nuevos mensajes de conversaciones individuales

**Comment by enolgargon** [comment]
Mi idea es crear un archivo por cada notificación que el usuario reciba.
Propongo crear la siguiente nomenclatura.
dechat<hash de 16 digitos con la url del que notifica><hora en la que se manda>
Pongo un ejemplo:
Andrés tiene el POD https://acg96.inrupt.net/profile/card#me, que se corresponde con el hash en md5 E83BC98E28E02706FF6FC9820731061A
Si me manda un mensaje el 1 de abril a las 9:30, se almacenaría en mi Inbox un archivo con el nombre: dechatE83BC98E28E02706FF6FC9820731061A201904010930
Si luego me manda otro a las 10:00 se guardaría otro archivo distinto con el nombre dechatE83BC98E28E02706FF6FC9820731061A201904011000
Con esa información se pueden listar todos los archivos y ordenarlos alfabéticamente para procesarlos.

Con respecto al contenido del fichero, yo pronpongo usar este modelo: https://schema.org/InformAction. Así el contenido del fichero podría ser algo como:
:notification
  schema:agent <https://arc96.inrupt.net/profile/card#me>,
  schema:event (Algo que indique que es un mensaje nuevo)
La ventaja de usar esto es que cuando incluyamos los grupos se podría utilizar el esquema https://schema.org/JoinAction que es idéntico

**Comment by acg96** [comment]
La idea que tenía era similar a esa, solo que la fecha del final indicada en milisegundos para evitar duplicidad de documentos y dentro de cada uno almacenar la URI de quien envía el mensaje y el contenido del mensaje.
En relación a los grupos sería lo mismo, solamente añadiendo dentro del archivo un array de las URI de los integrantes del grupo, la URI del que envía ese mensaje en concreto y el contenido del mensaje. No obstante esta issue está enfocada a conversaciones individuales.
