### ISSUE TITLE
Historias de usuario

### ISSUE THREAD

**Issue by enolgargon** [Arquisoft/dechat_es2b#78]
A ver qué historias se nos ocurren para hacer los tests.

Como usuario quiero poder seleccionar un contacto para ver todos los mensajes que he recibido de él
Como usuario quiero poder envíar un mensaje
Como usuario quiero ver los contactos que tengo
Como usuario quiero editar el nick de un contacto
Como usuario quiero crear un contacto nuevo

**Comment by acg96** [comment]
Como un usuario quiero poder eliminar un contacto
Como un usuario quiero poder crear conversaciones grupales
Como un usuario quiero poder borrar conversaciones grupales

**Comment by TomasArguelles** [comment]
Como usuario quiero poder exportar una o varias conversaciones
Como usuario quiero poder importar conversaciones

**Comment by enolgargon** [comment]
Como usuario desconectado quiero poder iniciar sesión
Como usuario logeado quiero poder desconectarme
